version: '3.5'
services:
  api01:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
     resources:
      limits:
       cpus: "0.525"
       memory: "210MB"
    networks:
      - rinha-backend

#  api02:
#    build: .
#    depends_on:
#      - db
#    deploy:
#     resources:
#      limits:
#        cpus: "0.525"
#        memory: "210MB"

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha-backend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
            cpus: "0.4"
            memory: "120MB"
    networks:
      - rinha-backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.config:/etc/nginx/nginx.config:ro
    depends_on:
      - api01
    deploy:
      resources:
        limits:
            cpus: "0.05"
            memory: "10MB"
    ports:
      - "9999:9999"
    networks:
      - rinha-backend

networks:
  rinha-backend:
    driver: bridge

