services:
  api01:
#      image: eduardodandolini/rinha-backend:tagname
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
       resources:
        limits:
         cpus: "0.35"
         memory: "80MB"
    networks:
      - rinha-backend

  api02:
#      image: eduardodandolini/rinha-backend:tagname
      build: .
      ports:
        - "8082:8080"
      depends_on:
        - db
      deploy:
        resources:
          limits:
            cpus: "0.35"
            memory: "80MB"
      networks:
        - rinha-backend

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha-backend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
            cpus: "0.6"
            memory: "340MB"
    networks:
      - rinha-backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.config:/etc/nginx/nginx.config:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
            cpus: "0.2"
            memory: "50MB"
    ports:
      - "9999:9999"
    networks:
      - rinha-backend

networks:
  rinha-backend:
    driver: bridge

